version: '3'

services: 
  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb:/var/lib/mysql

  redis:
    image: redis:latest

  frappe:
    build: .
    command: bench start
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
      - redis
    environment:
      - SITE_NAME=test_site
      - ADMIN_PWD=admin
      - DB_ROOT_PWD=
    volumes:
      - sites_volume:/home/frappe/frappe-bench/sites

volumes:
  mariadb:
  redis:
  sites_volume:
